### ISSUE TITLE
Constant "Error opening input: No such file or directory"

### ISSUE THREAD

**Issue by Scoovy** [Firebow59/SofdecVideoTools#1]
i'm having issues when creating the SFD file as it says "SFD couldn't be properly created. Try creating the file again" when retrying it keeps doing the same error,
in the Command prompt i get this error "Error opening input: No such file or directory" even though the file and directory both exist.

in the CMD menu it also says "System cannot the specified file: 'AVIconvert.avi'

I recorded a video of the exact steps i made when trying this tool out (note that FFMPEG is installed to PATH)

[https://www.youtube.com/watch?v=Tu78ifdP744](url)

**Comment by FutonGama** [comment]
same problem here, worked yesterday and today just stopped to work

**Comment by FutonGama** [comment]
this problem is related to the video name for some reason, when i change the video for another name depending the name the video convert i don't get it, and for every diferent video need to try diferent names to work, i'm trying to understand the logic behind this

**Comment by Firebow59** [comment]
I'm currently working on a fix, hoping to have it out within the next couple days at the latest.

**Comment by Firebow59** [comment]
The issue should be fixed now, try downloading the latest version and see if it fixes the issue.

**Comment by FutonGama** [comment]
Not worked for me, still give the error. One information, i'm using Python 1.10.6 Added to PATH. Not Python 11. I tested with 11 in older version and don't worked also, but i don't tested on the new version with Python 11. I don't use Python 11 only because i have other programs using python 1.10.6. Can you confirm if needs Python 11? 

This problem is odd, sometimes moving to another folder work, sometimes don't ... i don't get it.
