### ISSUE TITLE
sfd version 1 and 2 do not play in the gdi

### ISSUE THREAD

**Issue by hunkh** [Firebow59/SofdecVideoTools#9]
The sfd created in version 1 and do not start in the resident evil 3 dreamcast game only show black screens

**Comment by Firebow59** [comment]
Hey there! Some games have locks on what the resolution and the amount of possible audio tracks, one of which appears to be RE3.

The next version of SFDCreator will help support games like this due to a re-write of the audio system, and custom resolutions for V1 SFDs, but in the meantime, you can encode the SFDs for RE3 by using [this script](https://mega.nz/file/2Cp3nBxL#h9BnZ5zHZZFudCftn6g6vXMfz-1BeIbicKIDH_z_P_Y). Copy the files from it into your SofdecVideoTools folder, alongside the other EXE files.
